package Programme;

import About.About;
import Academics.Academics;
import Admission.Admission;
import CampusLife.CampusLife;
import Contact.Contact;
import LogIn.LogIn;
import Reasearch.Reasearch;
import SubButtons.SubButtons;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Programme {
    public Programme() {

        JFrame frame = new JFrame("Programme Overview");
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(null);
        frame.getContentPane().setBackground(Color.LIGHT_GRAY);

        SubButtons btn = new SubButtons(frame);

        // About
        JButton btn1 = new JButton("About");
        btn1.setFont(new Font("Arial", Font.BOLD, 23));
        btn1.setBounds(20, 140, 150, 40);
        btn1.setBackground(Color.WHITE);
        btn1.setForeground(Color.BLACK);
        btn1.setOpaque(false);
        frame.add(btn1);
        btn1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new About();
                frame.dispose();
            }
        });

        // Academics
        JButton btn3 = new JButton("Academics");
        btn3.setFont(new Font("Arial", Font.BOLD, 23));
        btn3.setBounds(390, 140, 170, 40);
        btn3.setBackground(Color.WHITE);
        btn3.setForeground(Color.BLACK);
        btn3.setOpaque(false);
        frame.add(btn3);
        btn3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new Academics();
                frame.dispose();
            }
        });

        // Admission
        JButton btn4 = new JButton("Admission");
        btn4.setFont(new Font("Arial", Font.BOLD, 23));
        btn4.setBounds(580, 140, 170, 40);
        btn4.setBackground(Color.WHITE);
        btn4.setForeground(Color.BLACK);
        btn4.setOpaque(false);
        frame.add(btn4);
        btn4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new Admission();
                frame.dispose();
            }
        });

        // Research
        JButton btn5 = new JButton("Research");
        btn5.setFont(new Font("Arial", Font.BOLD, 23));
        btn5.setBounds(770, 140, 160, 40);
        btn5.setBackground(Color.WHITE);
        btn5.setForeground(Color.BLACK);
        btn5.setOpaque(false);
        frame.add(btn5);
        btn5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new Reasearch();
                frame.dispose();
            }
        });

        // Campus Life
        JButton btn6 = new JButton("Campus Life");
        btn6.setFont(new Font("Arial", Font.BOLD, 23));
        btn6.setBounds(950, 140, 180, 40);
        btn6.setBackground(Color.WHITE);
        btn6.setForeground(Color.BLACK);
        btn6.setOpaque(false);
        frame.add(btn6);
        btn6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new CampusLife();
                frame.dispose();
            }
        });

        // Contact
        JButton btn7 = new JButton("Contact");
        btn7.setFont(new Font("Arial", Font.BOLD, 23));
        btn7.setBounds(1150, 140, 170, 40);
        btn7.setBackground(Color.WHITE);
        btn7.setForeground(Color.BLACK);
        btn7.setOpaque(false);
        frame.add(btn7);
        btn7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new Contact();
                frame.dispose();
            }
        });

        // Log in
        JButton btn8 = new JButton("Log in");
        btn8.setFont(new Font("Arial", Font.BOLD, 23));
        btn8.setBounds(1340, 140, 170, 40);
        btn8.setBackground(Color.WHITE);
        btn8.setForeground(Color.BLACK);
        btn8.setOpaque(false);
        frame.add(btn8);
        btn8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new LogIn();
                frame.dispose();
            }
        });


        JPanel pnl = new JPanel();
        pnl.setLayout(null);
        pnl.setBounds(250, 240, 1270, 50);
        pnl.setBackground(Color.WHITE);
        frame.add(pnl);
        JLabel lbl1 = new JLabel("Overview");
        lbl1.setBounds(10, 5, 1270, 40);
        lbl1.setFont(new Font("Arial", Font.BOLD, 28));
        lbl1.setForeground(Color.BLACK);
        pnl.add(lbl1);
        frame.add(pnl);

        JPanel pnl1 = new JPanel();
        pnl1.setLayout(null);
        pnl1.setBounds(250, 295, 1270, 90);
        pnl1.setBackground(Color.WHITE);
        frame.add(pnl1);
        JLabel lbl2 = new JLabel("Vision:");
        lbl2.setBounds(20, 5, 200, 30);
        lbl2.setFont(new Font("Arial", Font.BOLD, 20));
        pnl1.add(lbl2);
        JLabel lbl3 = new JLabel("To provide top-quality education across ENG, BBA, CSE, EEE, SWE, ECO, and LLB departments, fostering knowledge, innovation, ethical values, critical thinking, and leadership,");
        lbl3.setBounds(20, 35, 1250, 25);
        lbl3.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl1.add(lbl3);
        JLabel lbl4 = new JLabel("preparing students as competent global citizens.");
        lbl4.setBounds(20, 60, 1250, 25);
        lbl4.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl1.add(lbl4);
        frame.add(pnl1);

        JPanel pnl2 = new JPanel();
        pnl2.setLayout(null);
        pnl2.setBounds(250, 390, 1270, 140);
        pnl2.setBackground(Color.WHITE);
        frame.add(pnl2);
        JLabel lbl5 = new JLabel("Mission:");
        lbl5.setBounds(20, 5, 200, 30);
        lbl5.setFont(new Font("Arial", Font.BOLD, 20));
        pnl2.add(lbl5);
        JLabel lbl6 = new JLabel("• Deliver high-quality education across all departments with practical learning and modern teaching methods.");
        lbl6.setBounds(20, 35, 1250, 25);
        lbl6.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl2.add(lbl6);
        JLabel lbl7 = new JLabel("• Promote research, innovation, and critical thinking to ensure academic excellence and problem-solving skills.");
        lbl7.setBounds(20, 60, 1250, 25);
        lbl7.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl2.add(lbl7);
        JLabel lbl8 = new JLabel("• Prepare graduates for successful careers, higher studies, and lifelong learning in national and international contexts.");
        lbl8.setBounds(20, 85, 1250, 25);
        lbl8.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl2.add(lbl8);
        JLabel lbl9 = new JLabel("• Instill ethics, leadership, and social responsibility in students across all disciplines.");
        lbl9.setBounds(20, 110, 1250, 25);
        lbl9.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl2.add(lbl9);
        frame.add(pnl2);

        JPanel pnl3 = new JPanel();
        pnl3.setLayout(null);
        pnl3.setBounds(250, 535, 1270, 205);
        pnl3.setBackground(Color.WHITE);
        frame.add(pnl3);
        JLabel lbl10 = new JLabel("Future Goals:");
        lbl10.setBounds(20, 5, 200, 30);
        lbl10.setFont(new Font("Arial", Font.BOLD, 20));
        pnl3.add(lbl10);
        JLabel lbl11 = new JLabel("• Expand academic programs, modern facilities, research labs, and innovative learning environments for all departments.");
        lbl11.setBounds(20, 35, 1250, 25);
        lbl11.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl11);
        JLabel lbl12 = new JLabel("• Strengthen collaborations with industries, internships, and research opportunities to enhance practical exposure and employability.");
        lbl12.setBounds(20, 60, 1250, 25);
        lbl12.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl12);
        JLabel lbl13 = new JLabel("• Produce globally competent graduates from ENG, BBA, CSE, EEE, SWE, ECO, and LLB who can lead in innovation and society.");
        lbl13.setBounds(20, 85, 1250, 25);
        lbl13.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl13);
        JLabel lbl14 = new JLabel("• Introduce advanced digital learning tools and smart classrooms to improve teaching and learning outcomes.");
        lbl14.setBounds(20, 110, 1250, 25);
        lbl14.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl14);
        JLabel lbl15 = new JLabel("• Foster international collaborations, student exchange programs, and global research partnerships.");
        lbl15.setBounds(20, 135, 1250, 25);
        lbl15.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl15);
        JLabel lbl16 = new JLabel("• Encourage entrepreneurship and startup initiatives among students across all departments.");
        lbl16.setBounds(20, 160, 1250, 25);
        lbl16.setFont(new Font("Arial", Font.PLAIN, 16));
        pnl3.add(lbl16);
        frame.add(pnl3);




        JPanel pnl4 = new JPanel();
        pnl4.setLayout(null);
        pnl4.setBounds(250, 240, 1270, 40);
        pnl4.setOpaque(true);
        pnl4.setBackground(Color.white);
        pnl4.setVisible(false);
        JLabel lbl17 = new JLabel("B.A. (Hons.) in English Admission");
        lbl17.setBounds(10, 5, 1250, 35);
        lbl17.setFont(new Font("Arial", Font.BOLD, 25));
        lbl17.setForeground(Color.BLACK);
        pnl4.add(lbl17);
        frame.add(pnl4);

        JPanel pnl5 = new JPanel();
        pnl5.setLayout(null);
        pnl5.setBounds(250, 285, 1270, 60);
        pnl5.setOpaque(true);
        pnl5.setBackground(Color.white);
        pnl5.setVisible(false);
        JLabel lbl18 = new JLabel("Duration: 4 Years");
        lbl18.setBounds(10, 5, 150, 22);
        lbl18.setFont(new Font("Arial", Font.BOLD, 17));
        lbl18.setForeground(Color.BLACK);
        pnl5.add(lbl18);
        JLabel lbl19 = new JLabel("Schedule: Day");
        lbl19.setBounds(200, 5, 350, 22);
        lbl19.setFont(new Font("Arial", Font.BOLD, 17));
        lbl19.setForeground(Color.BLACK);
        pnl5.add(lbl19);
        JLabel lbl20 = new JLabel("Total Credits: 123");
        lbl20.setBounds(10, 30, 150, 22);
        lbl20.setFont(new Font("Arial", Font.BOLD, 17));
        lbl20.setForeground(Color.BLACK);
        pnl5.add(lbl20);
        JLabel lbl21 = new JLabel("Entry Time: January/May/September");
        lbl21.setBounds(200, 30, 350, 22);
        lbl21.setFont(new Font("Arial", Font.BOLD, 17));
        lbl21.setForeground(Color.BLACK);
        pnl5.add(lbl21);
        frame.add(pnl5);

        JPanel pnl6 = new JPanel();
        pnl6.setLayout(null);
        pnl6.setBounds(250, 350, 1270, 105);
        pnl6.setOpaque(true);
        pnl6.setBackground(Color.white);
        pnl6.setVisible(false);
        JLabel lbl22 = new JLabel("Programme Summary:");
        lbl22.setBounds(10, 5, 1250, 25);
        lbl22.setFont(new Font("Arial", Font.BOLD, 20));
        lbl22.setForeground(Color.BLACK);
        pnl6.add(lbl22);
        JLabel lbl23 = new JLabel("The era of post-modern EAdmission has now, more than ever, wider peripheries of needs, richer ideas to explore and better prospects to share. EAdmission now means more than a literature or");
        lbl23.setBounds(10, 35, 1250, 20);
        lbl23.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl23.setForeground(Color.BLACK);
        pnl6.add(lbl23);
        JLabel lbl24 = new JLabel("a language, and is considered a gateway to teaching, creative writing, journalism, information technology, management and administration. MU with this aim in view, offers Bachelor of Arts");
        lbl24.setBounds(10, 55, 1250, 20);
        lbl24.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl24.setForeground(Color.BLACK);
        pnl6.add(lbl24);
        JLabel lbl25 = new JLabel("in EAdmission and Masters of Arts (Preliminary & Final). The courses have been designed to equip our students with the kind of expertise they would require  to face life as global citizens.");
        lbl25.setBounds(10, 75, 1250, 20);
        lbl25.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl25.setForeground(Color.BLACK);
        pnl6.add(lbl25);
        frame.add(pnl6);

        JPanel pnl7 = new JPanel();
        pnl7.setLayout(null);
        pnl7.setBounds(250, 460, 1270, 180);
        pnl7.setOpaque(true);
        pnl7.setBackground(Color.white);
        pnl7.setVisible(false);
        JLabel lbl26 = new JLabel("Fees & Funding:");
        lbl26.setBounds(10, 5, 1250, 25);
        lbl26.setFont(new Font("Arial", Font.BOLD, 20));
        lbl26.setForeground(Color.BLACK);
        pnl7.add(lbl26);
        JLabel lbl27 = new JLabel("Metropolitan University provides financial support to the students and there is a caring tuition fee policy available to give financial aid. The students having Golden  A+ in both SSC & HSC ");
        lbl27.setBounds(10, 35, 1250, 20);
        lbl27.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl27.setForeground(Color.BLACK);
        pnl7.add(lbl27);
        JLabel lbl28 = new JLabel("will be given 50% tuition waiver.");
        lbl28.setBounds(10, 55, 1250, 20);
        lbl28.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl28.setForeground(Color.BLACK);
        pnl7.add(lbl28);
        JLabel lbl29 = new JLabel("Metropolitan University has various scholarship schemes to support the students financially.");
        lbl29.setBounds(10, 75, 1250, 20);
        lbl29.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl29.setForeground(Color.BLACK);
        pnl7.add(lbl29);
        JLabel lbl30 = new JLabel("A student who has secured A+ in all the courses in three consecutive term examinations can apply for Chairman’s Scholarship. Likewise, Vice Chancellor’s Scholarship also exists for ");
        lbl30.setBounds(10, 95, 1250, 20);
        lbl30.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl30.setForeground(Color.BLACK);
        pnl7.add(lbl30);
        JLabel lbl31 = new JLabel("the students of Metropolitan University.");
        lbl31.setBounds(10, 115, 1250, 20);
        lbl31.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl31.setForeground(Color.BLACK);
        pnl7.add(lbl31);
        JLabel lbl32 = new JLabel("Admission Fee (One time): 20,000");
        lbl32.setBounds(10, 135, 320, 17);
        lbl32.setFont(new Font("Arial", Font.BOLD, 14));
        lbl32.setForeground(Color.BLACK);
        pnl7.add(lbl32);
        JLabel lbl33 = new JLabel("Registration Fee (Per term): 10,000");
        lbl33.setBounds(10, 155, 320, 17);
        lbl33.setFont(new Font("Arial", Font.BOLD, 14));
        lbl33.setForeground(Color.BLACK);
        pnl7.add(lbl33);
        JLabel lbl34 = new JLabel("BNCC Fee (One time): 100");
        lbl34.setBounds(320, 135, 320, 17);
        lbl34.setFont(new Font("Arial", Font.BOLD, 14));
        lbl34.setForeground(Color.BLACK);
        pnl7.add(lbl34);
        JLabel lbl35 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl35.setBounds(320, 155, 320, 17);
        lbl35.setFont(new Font("Arial", Font.BOLD, 14));
        lbl35.setForeground(Color.BLACK);
        pnl7.add(lbl35);
        JLabel lbl36 = new JLabel("Monthly Installment of Credit Fees: 4,000");
        lbl36.setBounds(670, 135, 320, 17);
        lbl36.setFont(new Font("Arial", Font.BOLD, 14));
        lbl36.setForeground(Color.BLACK);
        pnl7.add(lbl36);
        frame.add(pnl7);

        JPanel pnl8 = new JPanel();
        pnl8.setLayout(null);
        pnl8.setBounds(250, 645, 1270, 95);
        pnl8.setOpaque(true);
        pnl8.setBackground(Color.white);
        pnl8.setVisible(false);
        JLabel lbl37 = new JLabel("How to apply:");
        lbl37.setBounds(10, 5, 320, 22);
        lbl37.setFont(new Font("Arial", Font.BOLD, 18));
        lbl37.setForeground(Color.BLACK);
        pnl8.add(lbl37);
        JLabel lbl38 = new JLabel("Submit the completed application form to the Admissions Office with the required documents:");
        lbl38.setBounds(10, 27, 1260, 20);
        lbl38.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl38.setForeground(Color.BLACK);
        pnl8.add(lbl38);
        JLabel lbl39 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl39.setBounds(10, 50, 420, 17);
        lbl39.setFont(new Font("Arial", Font.BOLD, 14));
        lbl39.setForeground(Color.BLACK);
        pnl8.add(lbl39);
        JLabel lbl40 = new JLabel("Four (04) copies of Passport size colour photographs.");
        lbl40.setBounds(10, 70, 420, 16);
        lbl40.setFont(new Font("Arial", Font.BOLD, 14));
        lbl40.setForeground(Color.BLACK);
        pnl8.add(lbl40);
        JLabel lbl41 = new JLabel("Blood Group.");
        lbl41.setBounds(430, 50, 500, 17);
        lbl41.setFont(new Font("Arial", Font.BOLD, 14));
        lbl41.setForeground(Color.BLACK);
        pnl8.add(lbl41);
        JLabel lbl42 = new JLabel("Original and one set of Photocopy of all Educational Certificates & Mark sheets.");
        lbl42.setBounds(430, 70, 570, 17);
        lbl42.setFont(new Font("Arial", Font.BOLD, 14));
        lbl42.setForeground(Color.BLACK);
        pnl8.add(lbl42);
        frame.add(pnl8);




        JPanel pnl9 = new JPanel();
        pnl9.setLayout(null);
        pnl9.setBounds(250, 240, 1260, 40);
        pnl9.setOpaque(true);
        pnl9.setBackground(Color.white);
        pnl9.setVisible(false);
        JLabel lbl43 = new JLabel("Bachelor of Business Administration Admission");
        lbl43.setBounds(10, 5, 1250, 35);
        lbl43.setFont(new Font("Arial", Font.BOLD, 25));
        lbl43.setForeground(Color.BLACK);
        pnl9.add(lbl43);
        frame.add(pnl9);

        JPanel pnl10 = new JPanel();
        pnl10.setLayout(null);
        pnl10.setBounds(250, 285, 1260, 60);
        pnl10.setOpaque(true);
        pnl10.setBackground(Color.white);
        pnl10.setVisible(false);
        JLabel lbl44 = new JLabel("Duration: 4 Years");
        lbl44.setBounds(10, 5, 150, 22);
        lbl44.setFont(new Font("Arial", Font.BOLD, 17));
        lbl44.setForeground(Color.BLACK);
        pnl10.add(lbl44);
        JLabel lbl45 = new JLabel("Schedule: Day");
        lbl45.setBounds(200, 5, 350, 22);
        lbl45.setFont(new Font("Arial", Font.BOLD, 17));
        lbl45.setForeground(Color.BLACK);
        pnl10.add(lbl45);
        JLabel lbl46 = new JLabel("Total Credits: 123");
        lbl46.setBounds(10, 30, 150, 22);
        lbl46.setFont(new Font("Arial", Font.BOLD, 17));
        lbl46.setForeground(Color.BLACK);
        pnl10.add(lbl46);
        JLabel lbl47 = new JLabel("Entry Time: January/May/September");
        lbl47.setBounds(200, 30, 350, 22);
        lbl47.setFont(new Font("Arial", Font.BOLD, 17));
        lbl47.setForeground(Color.BLACK);
        pnl10.add(lbl47);
        frame.add(pnl10);

        JPanel pnl11 = new JPanel();
        pnl11.setLayout(null);
        pnl11.setBounds(250, 350, 1260, 105);
        pnl11.setOpaque(true);
        pnl11.setBackground(Color.white);
        pnl11.setVisible(false);
        JLabel lbl48 = new JLabel("Programme Summary:");
        lbl48.setBounds(10, 5, 1250, 25);
        lbl48.setFont(new Font("Arial", Font.BOLD, 20));
        lbl48.setForeground(Color.BLACK);
        pnl11.add(lbl48);
        JLabel lbl49 = new JLabel("BAdmission Administration Department offers a 4-year Bachelor degree called ‘Bachelor of BAdmission Administration’. To become a graduate in this field, one has to complete 123 credits.");
        lbl49.setBounds(10, 35, 1250, 20);
        lbl49.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl49.setForeground(Color.BLACK);
        pnl11.add(lbl49);
        JLabel lbl50 = new JLabel("This program equips students with essential business and management skills to become effective leaders, innovators, and entrepreneurs. It provides strong academic training along with");
        lbl50.setBounds(10, 55, 1250, 20);
        lbl50.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl50.setForeground(Color.BLACK);
        pnl11.add(lbl50);
        JLabel lbl51 = new JLabel("broad knowledge in related fields, preparing graduates to perform successfully in private, public, NGO sectors, and small enterprises.");
        lbl51.setBounds(10, 75, 1250, 20);
        lbl51.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl51.setForeground(Color.BLACK);
        pnl11.add(lbl51);
        frame.add(pnl11);

        JPanel pnl12 = new JPanel();
        pnl12.setLayout(null);
        pnl12.setBounds(250, 460, 1260, 180);
        pnl12.setOpaque(true);
        pnl12.setBackground(Color.white);
        pnl12.setVisible(false);
        JLabel lbl52 = new JLabel("Fees & Funding:");
        lbl52.setBounds(10, 5, 1250, 25);
        lbl52.setFont(new Font("Arial", Font.BOLD, 20));
        lbl52.setForeground(Color.BLACK);
        pnl12.add(lbl52);
        JLabel lbl53 = new JLabel("Metropolitan University provides financial support to the students and has a caring tuition fee policy...");
        lbl53.setBounds(10, 35, 1250, 20);
        lbl53.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl53.setForeground(Color.BLACK);
        pnl12.add(lbl53);
        JLabel lbl54 = new JLabel("Students with Golden A+ in both SSC & HSC receive 50% tuition waiver.");
        lbl54.setBounds(10, 55, 1250, 20);
        lbl54.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl54.setForeground(Color.BLACK);
        pnl12.add(lbl54);
        JLabel lbl55 = new JLabel("MU also offers various scholarship schemes.");
        lbl55.setBounds(10, 75, 1250, 20);
        lbl55.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl55.setForeground(Color.BLACK);
        pnl12.add(lbl55);
        JLabel lbl56 = new JLabel("Chairman’s & VC Scholarships are available for high-performing students.");
        lbl56.setBounds(10, 95, 1250, 20);
        lbl56.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl56.setForeground(Color.BLACK);
        pnl12.add(lbl56);
        JLabel lbl57 = new JLabel("Admission Fee (One time): 20,000");
        lbl57.setBounds(10, 135, 320, 17);
        lbl57.setFont(new Font("Arial", Font.BOLD, 14));
        lbl57.setForeground(Color.BLACK);
        pnl12.add(lbl57);
        JLabel lbl58 = new JLabel("Registration Fee (Per term): 10,000");
        lbl58.setBounds(10, 155, 320, 17);
        lbl58.setFont(new Font("Arial", Font.BOLD, 14));
        lbl58.setForeground(Color.BLACK);
        pnl12.add(lbl58);
        frame.add(pnl12);

        JPanel pnl13 = new JPanel();
        pnl13.setLayout(null);
        pnl13.setBounds(250, 645, 1260, 95);
        pnl13.setOpaque(true);
        pnl13.setBackground(Color.white);
        pnl13.setVisible(false);
        JLabel lbl59 = new JLabel("How to apply:");
        lbl59.setBounds(10, 5, 320, 22);
        lbl59.setFont(new Font("Arial", Font.BOLD, 18));
        lbl59.setForeground(Color.BLACK);
        pnl13.add(lbl59);
        JLabel lbl60 = new JLabel("Submit the completed application form with required documents:");
        lbl60.setBounds(10, 27, 1260, 20);
        lbl60.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl60.setForeground(Color.BLACK);
        pnl13.add(lbl60);
        JLabel lbl61 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl61.setBounds(10, 50, 420, 17);
        lbl61.setFont(new Font("Arial", Font.BOLD, 14));
        lbl61.setForeground(Color.BLACK);
        pnl13.add(lbl61);
        JLabel lbl62 = new JLabel("Four copies of Passport size colour photographs.");
        lbl62.setBounds(10, 70, 420, 16);
        lbl62.setFont(new Font("Arial", Font.BOLD, 14));
        lbl62.setForeground(Color.BLACK);
        pnl13.add(lbl62);
        JLabel lbl63 = new JLabel("Blood Group.");
        lbl63.setBounds(430, 50, 500, 17);
        lbl63.setFont(new Font("Arial", Font.BOLD, 14));
        lbl63.setForeground(Color.BLACK);
        pnl13.add(lbl63);
        JLabel lbl64 = new JLabel("Original and one set of photocopy of all certificates & mark sheets.");
        lbl64.setBounds(430, 70, 570, 17);
        lbl64.setFont(new Font("Arial", Font.BOLD, 14));
        lbl64.setForeground(Color.BLACK);
        pnl13.add(lbl64);
        frame.add(pnl13);




        JPanel pnl14 = new JPanel();
        pnl14.setLayout(null);
        pnl14.setBounds(250, 240, 1260, 40);
        pnl14.setOpaque(true);
        pnl14.setBackground(Color.white);
        pnl14.setVisible(false);
        JLabel lbl65 = new JLabel("BSc. in Computer Science & Engineering Admission");
        lbl65.setBounds(10, 5, 1250, 35);
        lbl65.setFont(new Font("Arial", Font.BOLD, 25));
        lbl65.setForeground(Color.BLACK);
        pnl14.add(lbl65);
        frame.add(pnl14);

        JPanel pnl15 = new JPanel();
        pnl15.setLayout(null);
        pnl15.setBounds(250, 285, 1260, 60);
        pnl15.setOpaque(true);
        pnl15.setBackground(Color.white);
        pnl15.setVisible(false);
        JLabel lbl66 = new JLabel("Duration: 4 Years");
        lbl66.setBounds(10, 5, 150, 22);
        lbl66.setFont(new Font("Arial", Font.BOLD, 17));
        lbl66.setForeground(Color.BLACK);
        pnl15.add(lbl66);
        JLabel lbl67 = new JLabel("Schedule: Day/Evening");
        lbl67.setBounds(200, 5, 350, 22);
        lbl67.setFont(new Font("Arial", Font.BOLD, 17));
        lbl67.setForeground(Color.BLACK);
        pnl15.add(lbl67);
        JLabel lbl68 = new JLabel("Total Credits: 150");
        lbl68.setBounds(10, 30, 150, 22);
        lbl68.setFont(new Font("Arial", Font.BOLD, 17));
        lbl68.setForeground(Color.BLACK);
        pnl15.add(lbl68);
        JLabel lbl69 = new JLabel("Entry Time: January/May/September");
        lbl69.setBounds(200, 30, 350, 22);
        lbl69.setFont(new Font("Arial", Font.BOLD, 17));
        lbl69.setForeground(Color.BLACK);
        pnl15.add(lbl69);
        frame.add(pnl15);

        JPanel pnl16 = new JPanel();
        pnl16.setLayout(null);
        pnl16.setBounds(250, 350, 1260, 105);
        pnl16.setOpaque(true);
        pnl16.setBackground(Color.white);
        pnl16.setVisible(false);
        JLabel lbl70 = new JLabel("Programme Summary:");
        lbl70.setBounds(10, 5, 1250, 25);
        lbl70.setFont(new Font("Arial", Font.BOLD, 20));
        lbl70.setForeground(Color.BLACK);
        pnl16.add(lbl70);
        JLabel lbl71 = new JLabel("The B.Sc. in Computer Science and Engineering (CSE) is a 4-year program consisting of 8 semesters, requiring at least 150 credits for graduation. It is designed to provide students with");
        lbl71.setBounds(10, 35, 1250, 20);
        lbl71.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl71.setForeground(Color.BLACK);
        pnl16.add(lbl71);
        JLabel lbl72 = new JLabel("strong theoretical and technical knowledge in computer science. The demand for skilled professionals in Computer Science and Information Technology is rapidly growing in Bangladesh");
        lbl72.setBounds(10, 55, 1250, 20);
        lbl72.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl72.setForeground(Color.BLACK);
        pnl16.add(lbl72);
        JLabel lbl73 = new JLabel("and across the world. As technology continues to evolve, computer scientists will play a vital role in shaping the future and transforming the way we live and work.");
        lbl73.setBounds(10, 75, 1250, 20);
        lbl73.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl73.setForeground(Color.BLACK);
        pnl16.add(lbl73);
        frame.add(pnl16);

        JPanel pnl17 = new JPanel();
        pnl17.setLayout(null);
        pnl17.setBounds(250, 460, 1260, 180);
        pnl17.setOpaque(true);
        pnl17.setBackground(Color.white);
        pnl17.setVisible(false);
        JLabel lbl74 = new JLabel("Fees & Funding:");
        lbl74.setBounds(10, 5, 1250, 25);
        lbl74.setFont(new Font("Arial", Font.BOLD, 20));
        lbl74.setForeground(Color.BLACK);
        pnl17.add(lbl74);
        JLabel lbl75 = new JLabel("Metropolitan University provides financial support to the students and there is a caring tuition fee policy available to give financial aid. The students having Golden A+ in both SSC & HSC");
        lbl75.setBounds(10, 35, 1250, 20);
        lbl75.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl75.setForeground(Color.BLACK);
        pnl17.add(lbl75);
        JLabel lbl76 = new JLabel("will be given 50% tuition waiver.");
        lbl76.setBounds(10, 55, 1250, 20);
        lbl76.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl76.setForeground(Color.BLACK);
        pnl17.add(lbl76);
        JLabel lbl77 = new JLabel("Metropolitan University has various scholarship schemes to support the students financially.");
        lbl77.setBounds(10, 75, 1250, 20);
        lbl77.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl77.setForeground(Color.BLACK);
        pnl17.add(lbl77);
        JLabel lbl78 = new JLabel("A student who has secured A+ in all the courses in three consecutive term examinations can apply for Chairman’s Scholarship. Likewise, Vice Chancellor’s Scholarship also exists for");
        lbl78.setBounds(10, 95, 1250, 20);
        lbl78.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl78.setForeground(Color.BLACK);
        pnl17.add(lbl78);
        JLabel lbl79 = new JLabel("the students of Metropolitan University.");
        lbl79.setBounds(10, 115, 1250, 20);
        lbl79.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl79.setForeground(Color.BLACK);
        pnl17.add(lbl79);
        JLabel lbl80 = new JLabel("Admission Fee (One time): 20,000");
        lbl80.setBounds(10, 135, 320, 17);
        lbl80.setFont(new Font("Arial", Font.BOLD, 14));
        lbl80.setForeground(Color.BLACK);
        pnl17.add(lbl80);
        JLabel lbl81 = new JLabel("Registration Fee (Per term): 10,000");
        lbl81.setBounds(10, 155, 320, 17);
        lbl81.setFont(new Font("Arial", Font.BOLD, 14));
        lbl81.setForeground(Color.BLACK);
        pnl17.add(lbl81);
        JLabel lbl82 = new JLabel("BNCC Fee (One time): 100");
        lbl82.setBounds(320, 135, 320, 17);
        lbl82.setFont(new Font("Arial", Font.BOLD, 14));
        lbl82.setForeground(Color.BLACK);
        pnl17.add(lbl82);
        JLabel lbl83 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl83.setBounds(320, 155, 320, 17);
        lbl83.setFont(new Font("Arial", Font.BOLD, 14));
        lbl83.setForeground(Color.BLACK);
        pnl17.add(lbl83);
        JLabel lbl84 = new JLabel("Monthly Installment of Credit Fees: 6,000");
        lbl84.setBounds(670, 135, 320, 17);
        lbl84.setFont(new Font("Arial", Font.BOLD, 14));
        lbl84.setForeground(Color.BLACK);
        pnl17.add(lbl84);
        frame.add(pnl17);

        JPanel pnl18 = new JPanel();
        pnl18.setLayout(null);
        pnl18.setBounds(250, 645, 1260, 95);
        pnl18.setOpaque(true);
        pnl18.setBackground(Color.white);
        pnl18.setVisible(false);
        JLabel lbl85 = new JLabel("How to apply:");
        lbl85.setBounds(10, 5, 320, 22);
        lbl85.setFont(new Font("Arial", Font.BOLD, 18));
        lbl85.setForeground(Color.BLACK);
        pnl18.add(lbl85);
        JLabel lbl86 = new JLabel("Submit the completed application form to the Admissions Office with the required documents:");
        lbl86.setBounds(10, 27, 1260, 20);
        lbl86.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl86.setForeground(Color.BLACK);
        pnl18.add(lbl86);
        JLabel lbl87 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl87.setBounds(10, 50, 420, 17);
        lbl87.setFont(new Font("Arial", Font.BOLD, 14));
        lbl87.setForeground(Color.BLACK);
        pnl18.add(lbl87);
        JLabel lbl88 = new JLabel("Four (04) copies of Passport size colour photographs.");
        lbl88.setBounds(10, 70, 420, 16);
        lbl88.setFont(new Font("Arial", Font.BOLD, 14));
        lbl88.setForeground(Color.BLACK);
        pnl18.add(lbl88);
        JLabel lbl89 = new JLabel("Blood Group.");
        lbl89.setBounds(430, 50, 500, 17);
        lbl89.setFont(new Font("Arial", Font.BOLD, 14));
        lbl89.setForeground(Color.BLACK);
        pnl18.add(lbl89);
        JLabel lbl90 = new JLabel("Original and one set of Photocopy of all Educational Certificates & Mark sheets.");
        lbl90.setBounds(430, 70, 570, 17);
        lbl90.setFont(new Font("Arial", Font.BOLD, 14));
        lbl90.setForeground(Color.BLACK);
        pnl18.add(lbl90);
        frame.add(pnl18);




        JPanel pnl19 = new JPanel();
        pnl19.setLayout(null);
        pnl19.setBounds(250, 240, 1260, 40);
        pnl19.setOpaque(true);
        pnl19.setBackground(Color.white);
        JLabel lbl91 = new JLabel("BSc. in Electrical and Electronics Engineering Admission");
        lbl91.setBounds(10, 5, 1250, 35);
        lbl91.setFont(new Font("Arial", Font.BOLD, 25));
        lbl91.setForeground(Color.BLACK);
        pnl19.add(lbl91);
        pnl19.setVisible(false);
        frame.add(pnl19);

        JPanel pnl20 = new JPanel();
        pnl20.setLayout(null);
        pnl20.setBounds(250, 285, 1260, 60);
        pnl20.setOpaque(true);
        pnl20.setBackground(Color.white);
        JLabel lbl92 = new JLabel("Duration: 4 Years");
        lbl92.setBounds(10, 5, 150, 22);
        lbl92.setFont(new Font("Arial", Font.BOLD, 17));
        lbl92.setForeground(Color.BLACK);
        pnl20.add(lbl92);
        JLabel lbl93 = new JLabel("Schedule: Day");
        lbl93.setBounds(200, 5, 350, 22);
        lbl93.setFont(new Font("Arial", Font.BOLD, 17));
        lbl93.setForeground(Color.BLACK);
        pnl20.add(lbl93);
        JLabel lbl94 = new JLabel("Total Credits: 144");
        lbl94.setBounds(10, 30, 150, 22);
        lbl94.setFont(new Font("Arial", Font.BOLD, 17));
        lbl94.setForeground(Color.BLACK);
        pnl20.add(lbl94);
        JLabel lbl95 = new JLabel("Entry Time: January/May/September");
        lbl95.setBounds(200, 30, 350, 22);
        lbl95.setFont(new Font("Arial", Font.BOLD, 17));
        lbl95.setForeground(Color.BLACK);
        pnl20.add(lbl95);
        pnl20.setVisible(false);
        frame.add(pnl20);

        JPanel pnl21 = new JPanel();
        pnl21.setLayout(null);
        pnl21.setBounds(250, 350, 1260, 105);
        pnl21.setOpaque(true);
        pnl21.setBackground(Color.white);
        JLabel lbl96 = new JLabel("Programme Summary:");
        lbl96.setBounds(10, 5, 1250, 25);
        lbl96.setFont(new Font("Arial", Font.BOLD, 20));
        lbl96.setForeground(Color.BLACK);
        pnl21.add(lbl96);
        JLabel lbl97 = new JLabel("Electrical and Electronic Engineering (EEE) focuses on the study and application of electricity, electronics, and electromagnetism.");
        lbl97.setBounds(10, 35, 1250, 20);
        lbl97.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl97.setForeground(Color.BLACK);
        pnl21.add(lbl97);
        JLabel lbl98 = new JLabel("The field includes power engineering, electronics, control systems, signal processing, and related areas.");
        lbl98.setBounds(10, 55, 1250, 20);
        lbl98.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl98.setForeground(Color.BLACK);
        pnl21.add(lbl98);
        JLabel lbl99 = new JLabel("This program prepares graduates to work in private, public, NGO sectors, and various engineering industries.");
        lbl99.setBounds(10, 75, 1250, 20);
        lbl99.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl99.setForeground(Color.BLACK);
        pnl21.add(lbl99);
        pnl21.setVisible(false);
        frame.add(pnl21);

        JPanel pnl22 = new JPanel();
        pnl22.setLayout(null);
        pnl22.setBounds(250, 460, 1260, 180);
        pnl22.setOpaque(true);
        pnl22.setBackground(Color.white);
        JLabel lbl100 = new JLabel("Fees & Funding:");
        lbl100.setBounds(10, 5, 1250, 25);
        lbl100.setFont(new Font("Arial", Font.BOLD, 20));
        lbl100.setForeground(Color.BLACK);
        pnl22.add(lbl100);
        JLabel lbl101 = new JLabel("Metropolitan University provides financial support with a caring tuition fee policy.");
        lbl101.setBounds(10, 35, 1250, 20);
        lbl101.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl101.setForeground(Color.BLACK);
        pnl22.add(lbl101);
        JLabel lbl102 = new JLabel("Students having Golden A+ in both SSC & HSC receive 50% tuition waiver.");
        lbl102.setBounds(10, 55, 1250, 20);
        lbl102.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl102.setForeground(Color.BLACK);
        pnl22.add(lbl102);
        JLabel lbl103 = new JLabel("Various scholarship schemes are available, including Chairman’s and VC Scholarships.");
        lbl103.setBounds(10, 75, 1250, 20);
        lbl103.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl103.setForeground(Color.BLACK);
        pnl22.add(lbl103);
        JLabel lbl104 = new JLabel("Admission Fee (One time): 20,000");
        lbl104.setBounds(10, 135, 320, 17);
        lbl104.setFont(new Font("Arial", Font.BOLD, 14));
        lbl104.setForeground(Color.BLACK);
        pnl22.add(lbl104);
        JLabel lbl105 = new JLabel("Registration Fee (Per term): 10,000");
        lbl105.setBounds(10, 155, 320, 17);
        lbl105.setFont(new Font("Arial", Font.BOLD, 14));
        lbl105.setForeground(Color.BLACK);
        pnl22.add(lbl105);
        JLabel lbl106 = new JLabel("BNCC Fee (One time): 100");
        lbl106.setBounds(320, 135, 320, 17);
        lbl106.setFont(new Font("Arial", Font.BOLD, 14));
        lbl106.setForeground(Color.BLACK);
        pnl22.add(lbl106);
        JLabel lbl107 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl107.setBounds(320, 155, 320, 17);
        lbl107.setFont(new Font("Arial", Font.BOLD, 14));
        lbl107.setForeground(Color.BLACK);
        pnl22.add(lbl107);
        JLabel lbl108 = new JLabel("Monthly Installment of Credit Fees: 6,000");
        lbl108.setBounds(670, 135, 320, 17);
        lbl108.setFont(new Font("Arial", Font.BOLD, 14));
        lbl108.setForeground(Color.BLACK);
        pnl22.add(lbl108);
        pnl22.setVisible(false);
        frame.add(pnl22);

        JPanel pnl23 = new JPanel();
        pnl23.setLayout(null);
        pnl23.setBounds(250, 645, 1260, 95);
        pnl23.setOpaque(true);
        pnl23.setBackground(Color.white);
        JLabel lbl109 = new JLabel("How to apply:");
        lbl109.setBounds(10, 5, 320, 22);
        lbl109.setFont(new Font("Arial", Font.BOLD, 18));
        lbl109.setForeground(Color.BLACK);
        pnl23.add(lbl109);
        JLabel lbl110 = new JLabel("Submit the completed application form with the required documents:");
        lbl110.setBounds(10, 27, 1260, 20);
        lbl110.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl110.setForeground(Color.BLACK);
        pnl23.add(lbl110);
        JLabel lbl111 = new JLabel("Photocopies of Birth Certificate / National ID / Passport.");
        lbl111.setBounds(10, 50, 420, 17);
        lbl111.setFont(new Font("Arial", Font.BOLD, 14));
        lbl111.setForeground(Color.BLACK);
        pnl23.add(lbl111);
        JLabel lbl112 = new JLabel("Four passport-size photographs.");
        lbl112.setBounds(10, 70, 420, 16);
        lbl112.setFont(new Font("Arial", Font.BOLD, 14));
        lbl112.setForeground(Color.BLACK);
        pnl23.add(lbl112);
        JLabel lbl113 = new JLabel("Blood Group.");
        lbl113.setBounds(430, 50, 500, 17);
        lbl113.setFont(new Font("Arial", Font.BOLD, 14));
        lbl113.setForeground(Color.BLACK);
        pnl23.add(lbl113);
        JLabel lbl114 = new JLabel("Original and photocopy of all educational certificates and mark sheets.");
        lbl114.setBounds(430, 70, 570, 17);
        lbl114.setFont(new Font("Arial", Font.BOLD, 14));
        lbl114.setForeground(Color.BLACK);
        pnl23.add(lbl114);
        pnl23.setVisible(false);
        frame.add(pnl23);




        JPanel pnl24 = new JPanel();
        pnl24.setLayout(null);
        pnl24.setBounds(250, 240, 1260, 40);
        pnl24.setOpaque(true);
        pnl24.setBackground(Color.white);
        pnl24.setVisible(false);
        JLabel lbl124 = new JLabel("BSc. in Software Engineering Admission");
        lbl124.setBounds(10, 5, 1250, 35);
        lbl124.setFont(new Font("Arial", Font.BOLD, 25));
        lbl124.setForeground(Color.BLACK);
        pnl24.add(lbl124);
        frame.add(pnl24);

        JPanel pnl25 = new JPanel();
        pnl25.setLayout(null);
        pnl25.setBounds(250, 285, 1260, 60);
        pnl25.setOpaque(true);
        pnl25.setBackground(Color.white);
        pnl25.setVisible(false);
        JLabel lbl125 = new JLabel("Duration: 4 Years");
        lbl125.setBounds(10, 5, 150, 22);
        lbl125.setFont(new Font("Arial", Font.BOLD, 17));
        lbl125.setForeground(Color.BLACK);
        pnl25.add(lbl125);
        JLabel lbl126 = new JLabel("Schedule: Day/Evening");
        lbl126.setBounds(200, 5, 350, 22);
        lbl126.setFont(new Font("Arial", Font.BOLD, 17));
        lbl126.setForeground(Color.BLACK);
        pnl25.add(lbl126);
        JLabel lbl127 = new JLabel("Total Credits:160");
        lbl127.setBounds(10, 30, 150, 22);
        lbl127.setFont(new Font("Arial", Font.BOLD, 17));
        lbl127.setForeground(Color.BLACK);
        pnl25.add(lbl127);
        JLabel lbl128 = new JLabel("Entry Time: January/May/September");
        lbl128.setBounds(200, 30, 350, 22);
        lbl128.setFont(new Font("Arial", Font.BOLD, 17));
        lbl128.setForeground(Color.BLACK);
        pnl25.add(lbl128);
        frame.add(pnl25);

        JPanel pnl26 = new JPanel();
        pnl26.setLayout(null);
        pnl26.setBounds(250, 350, 1260, 105);
        pnl26.setOpaque(true);
        pnl26.setBackground(Color.white);
        pnl26.setVisible(false);
        JLabel lbl129 = new JLabel("Programme Summary:");
        lbl129.setBounds(10, 5, 1250, 25);
        lbl129.setFont(new Font("Arial", Font.BOLD, 20));
        lbl129.setForeground(Color.BLACK);
        pnl26.add(lbl129);
        JLabel lbl130 = new JLabel("The B.Sc. in Software Engineering is a 4-year undergraduate program requiring 160 credits, including 148 credits of theory and lab courses and a 12-credit internship at a reputed");
        lbl130.setBounds(10, 35, 1250, 20);
        lbl130.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl130.setForeground(Color.BLACK);
        pnl26.add(lbl130);
        JLabel lbl131 = new JLabel("software development firm. The curriculum follows an outcome-based structure, combining science and mathematics, general education, core computer science, and specialized software");
        lbl131.setBounds(10, 55, 1250, 20);
        lbl131.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl131.setForeground(Color.BLACK);
        pnl26.add(lbl131);
        JLabel lbl132 = new JLabel("engineering courses. Students gain software development and quality skills while staying updated with industry trends and striving for excellence.");
        lbl132.setBounds(10, 75, 1250, 20);
        lbl132.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl132.setForeground(Color.BLACK);
        pnl26.add(lbl132);
        frame.add(pnl26);

        JPanel pnl27 = new JPanel();
        pnl27.setLayout(null);
        pnl27.setBounds(250, 460, 1260, 180);
        pnl27.setOpaque(true);
        pnl27.setBackground(Color.white);
        pnl27.setVisible(false);
        JLabel lbl133 = new JLabel("Fees & Funding:");
        lbl133.setBounds(10, 5, 1250, 25);
        lbl133.setFont(new Font("Arial", Font.BOLD, 20));
        lbl133.setForeground(Color.BLACK);
        pnl27.add(lbl133);
        JLabel lbl134 = new JLabel("Metropolitan University provides financial support to the students and there is a caring tuition fee policy available to give financial aid. The students having Golden  A+ in both SSC & HSC ");
        lbl134.setBounds(10, 35, 1250, 20);
        lbl134.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl134.setForeground(Color.BLACK);
        pnl27.add(lbl134);
        JLabel lbl135 = new JLabel("will be given 50% tuition waiver.");
        lbl135.setBounds(10, 55, 1250, 20);
        lbl135.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl135.setForeground(Color.BLACK);
        pnl27.add(lbl135);
        JLabel lbl136 = new JLabel("Metropolitan University has various scholarship schemes to support the students financially.");
        lbl136.setBounds(10, 75, 1250, 20);
        lbl136.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl136.setForeground(Color.BLACK);
        pnl27.add(lbl136);
        JLabel lbl137 = new JLabel("A student who has secured A+ in all the courses in three consecutive term examinations can apply for Chairman’s Scholarship. Likewise, Vice Chancellor’s Scholarship also exists for ");
        lbl137.setBounds(10, 95, 1250, 20);
        lbl137.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl137.setForeground(Color.BLACK);
        pnl27.add(lbl137);
        JLabel lbl138 = new JLabel("the students of Metropolitan University.");
        lbl138.setBounds(10, 115, 1250, 20);
        lbl138.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl138.setForeground(Color.BLACK);
        pnl27.add(lbl138);
        JLabel lbl139 = new JLabel("Admission Fee (One time): 20,000");
        lbl139.setBounds(10, 135, 320, 17);
        lbl139.setFont(new Font("Arial", Font.BOLD, 14));
        lbl139.setForeground(Color.BLACK);
        pnl27.add(lbl139);
        JLabel lbl140 = new JLabel("Registration Fee (Per term): 10,000");
        lbl140.setBounds(10, 155, 320, 17);
        lbl140.setFont(new Font("Arial", Font.BOLD, 14));
        lbl140.setForeground(Color.BLACK);
        pnl27.add(lbl140);
        JLabel lbl141 = new JLabel("BNCC Fee (One time): 100");
        lbl141.setBounds(320, 135, 320, 17);
        lbl141.setFont(new Font("Arial", Font.BOLD, 14));
        lbl141.setForeground(Color.BLACK);
        pnl27.add(lbl141);
        JLabel lbl142 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl142.setBounds(320, 155, 320, 17);
        lbl142.setFont(new Font("Arial", Font.BOLD, 14));
        lbl142.setForeground(Color.BLACK);
        pnl27.add(lbl142);
        JLabel lbl143 = new JLabel("Monthly Installment of Credit Fees: 6,000");
        lbl143.setBounds(670, 135, 320, 17);
        lbl143.setFont(new Font("Arial", Font.BOLD, 14));
        lbl143.setForeground(Color.BLACK);
        pnl27.add(lbl143);
        frame.add(pnl27);

        JPanel pnl28 = new JPanel();
        pnl28.setLayout(null);
        pnl28.setBounds(250, 645, 1260, 95);
        pnl28.setOpaque(true);
        pnl28.setBackground(Color.white);
        pnl28.setVisible(false);
        JLabel lbl144 = new JLabel("How to apply:");
        lbl144.setBounds(10, 5, 320, 22);
        lbl144.setFont(new Font("Arial", Font.BOLD, 18));
        lbl144.setForeground(Color.BLACK);
        pnl28.add(lbl144);
        JLabel lbl145 = new JLabel("Submit the completed application form to the Admissions Office with the required documents:");
        lbl145.setBounds(10, 27, 1260, 20);
        lbl145.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl145.setForeground(Color.BLACK);
        pnl28.add(lbl145);
        JLabel lbl146 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl146.setBounds(10, 50, 420, 17);
        lbl146.setFont(new Font("Arial", Font.BOLD, 14));
        lbl146.setForeground(Color.BLACK);
        pnl28.add(lbl146);
        JLabel lbl147 = new JLabel("Four (04) copies of Passport size colour photographs.");
        lbl147.setBounds(10, 70, 420, 16);
        lbl147.setFont(new Font("Arial", Font.BOLD, 14));
        lbl147.setForeground(Color.BLACK);
        pnl28.add(lbl147);
        JLabel lbl148 = new JLabel("Blood Group.");
        lbl148.setBounds(430, 50, 500, 17);
        lbl148.setFont(new Font("Arial", Font.BOLD, 14));
        lbl148.setForeground(Color.BLACK);
        pnl28.add(lbl148);
        JLabel lbl149 = new JLabel("Original and one set of Photocopy of all Educational Certificates & Mark sheets.");
        lbl149.setBounds(430, 70, 570, 17);
        lbl149.setFont(new Font("Arial", Font.BOLD, 14));
        lbl149.setForeground(Color.BLACK);
        pnl28.add(lbl149);
        frame.add(pnl28);




        JPanel pnl29 = new JPanel();
        pnl29.setLayout(null);
        pnl29.setBounds(250, 240, 1260, 40);
        pnl29.setOpaque(true);
        pnl29.setBackground(Color.white);
        pnl29.setVisible(false);
        JLabel lbl150 = new JLabel("BSS in Economics Admission");
        lbl150.setBounds(10, 5, 1250, 35);
        lbl150.setFont(new Font("Arial", Font.BOLD, 25));
        lbl150.setForeground(Color.BLACK);
        pnl29.add(lbl150);
        frame.add(pnl29);

        JPanel pnl30 = new JPanel();
        pnl30.setLayout(null);
        pnl30.setBounds(250, 285, 1260, 60);
        pnl30.setOpaque(true);
        pnl30.setBackground(Color.white);
        pnl30.setVisible(false);
        JLabel lbl151 = new JLabel("Duration: 4 Years");
        lbl151.setBounds(10, 5, 150, 22);
        lbl151.setFont(new Font("Arial", Font.BOLD, 17));
        lbl151.setForeground(Color.BLACK);
        pnl30.add(lbl151);
        JLabel lbl152 = new JLabel("Schedule: Day");
        lbl152.setBounds(200, 5, 350, 22);
        lbl152.setFont(new Font("Arial", Font.BOLD, 17));
        lbl152.setForeground(Color.BLACK);
        pnl30.add(lbl152);
        JLabel lbl153 = new JLabel("Total Credits: 120");
        lbl153.setBounds(10, 30, 150, 22);
        lbl153.setFont(new Font("Arial", Font.BOLD, 17));
        lbl153.setForeground(Color.BLACK);
        pnl30.add(lbl153);
        JLabel lbl154 = new JLabel("Entry Time: January/May/September");
        lbl154.setBounds(200, 30, 350, 22);
        lbl154.setFont(new Font("Arial", Font.BOLD, 17));
        lbl154.setForeground(Color.BLACK);
        pnl30.add(lbl154);
        frame.add(pnl30);

        JPanel pnl31 = new JPanel();
        pnl31.setLayout(null);
        pnl31.setBounds(250, 350, 1260, 105);
        pnl31.setOpaque(true);
        pnl31.setBackground(Color.white);
        pnl31.setVisible(false);
        JLabel lbl155 = new JLabel("Programme Summary:");
        lbl155.setBounds(10, 5, 1250, 25);
        lbl155.setFont(new Font("Arial", Font.BOLD, 20));
        lbl155.setForeground(Color.BLACK);
        pnl31.add(lbl155);
        JLabel lbl156 = new JLabel("The Bachelor of Social Science in Economics (BSS in Economics) at Metropolitan University offers an internationally recognized undergraduate degree. The program is delivered by");
        lbl156.setBounds(10, 35, 1250, 20);
        lbl156.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl156.setForeground(Color.BLACK);
        pnl31.add(lbl156);
        JLabel lbl157 = new JLabel("highly qualified and experienced faculty, providing one of the leading Economics programs in Bangladesh. It prepares students for careers in banks, financial institutions, development");
        lbl157.setBounds(10, 55, 1250, 20);
        lbl157.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl157.setForeground(Color.BLACK);
        pnl31.add(lbl157);
        JLabel lbl158 = new JLabel("agencies, education, and research, while equipping them with knowledge of economic concepts, theories, techniques, public policy, and related fields in business and social sciences.");
        lbl158.setBounds(10, 75, 1250, 20);
        lbl158.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl158.setForeground(Color.BLACK);
        pnl31.add(lbl158);
        frame.add(pnl31);

        JPanel pnl32 = new JPanel();
        pnl32.setLayout(null);
        pnl32.setBounds(250, 460, 1260, 180);
        pnl32.setOpaque(true);
        pnl32.setBackground(Color.white);
        pnl32.setVisible(false);
        JLabel lbl159 = new JLabel("Fees & Funding:");
        lbl159.setBounds(10, 5, 1250, 25);
        lbl159.setFont(new Font("Arial", Font.BOLD, 20));
        lbl159.setForeground(Color.BLACK);
        pnl32.add(lbl159);
        JLabel lbl160 = new JLabel("Metropolitan University provides financial support to the students and there is a caring tuition fee policy available to give financial aid. The students having Golden  A+ in both SSC & HSC ");
        lbl160.setBounds(10, 35, 1250, 20);
        lbl160.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl160.setForeground(Color.BLACK);
        pnl32.add(lbl160);
        JLabel lbl161 = new JLabel("will be given 50% tuition waiver.");
        lbl161.setBounds(10, 55, 1250, 20);
        lbl161.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl161.setForeground(Color.BLACK);
        pnl32.add(lbl161);
        JLabel lbl162 = new JLabel("Metropolitan University has various scholarship schemes to support the students financially.");
        lbl162.setBounds(10, 75, 1250, 20);
        lbl162.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl162.setForeground(Color.BLACK);
        pnl32.add(lbl162);
        JLabel lbl163 = new JLabel("A student who has secured A+ in all the courses in three consecutive term examinations can apply for Chairman’s Scholarship. Likewise, Vice Chancellor’s Scholarship also exists for ");
        lbl163.setBounds(10, 95, 1250, 20);
        lbl163.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl163.setForeground(Color.BLACK);
        pnl32.add(lbl163);
        JLabel lbl164 = new JLabel("the students of Metropolitan University.");
        lbl164.setBounds(10, 115, 1250, 20);
        lbl164.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl164.setForeground(Color.BLACK);
        pnl32.add(lbl164);
        JLabel lbl165 = new JLabel("Admission Fee (One time): 20,000");
        lbl165.setBounds(10, 135, 320, 17);
        lbl165.setFont(new Font("Arial", Font.BOLD, 14));
        lbl165.setForeground(Color.BLACK);
        pnl32.add(lbl165);
        JLabel lbl166 = new JLabel("Registration Fee (Per term): 10,000");
        lbl166.setBounds(10, 155, 320, 17);
        lbl166.setFont(new Font("Arial", Font.BOLD, 14));
        lbl166.setForeground(Color.BLACK);
        pnl32.add(lbl166);
        JLabel lbl167 = new JLabel("BNCC Fee (One time): 100");
        lbl167.setBounds(320, 135, 320, 17);
        lbl167.setFont(new Font("Arial", Font.BOLD, 14));
        lbl167.setForeground(Color.BLACK);
        pnl32.add(lbl167);
        JLabel lbl168 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl168.setBounds(320, 155, 320, 17);
        lbl168.setFont(new Font("Arial", Font.BOLD, 14));
        lbl168.setForeground(Color.BLACK);
        pnl32.add(lbl168);
        JLabel lbl169 = new JLabel("Monthly Installment of Credit Fees: 6,000");
        lbl169.setBounds(670, 135, 320, 17);
        lbl169.setFont(new Font("Arial", Font.BOLD, 14));
        lbl169.setForeground(Color.BLACK);
        pnl32.add(lbl169);
        frame.add(pnl32);

        JPanel pnl33 = new JPanel();
        pnl33.setLayout(null);
        pnl33.setBounds(250, 645, 1260, 95);
        pnl33.setOpaque(true);
        pnl33.setBackground(Color.white);
        pnl33.setVisible(false);
        JLabel lbl170 = new JLabel("How to apply:");
        lbl170.setBounds(10, 5, 320, 22);
        lbl170.setFont(new Font("Arial", Font.BOLD, 18));
        lbl170.setForeground(Color.BLACK);
        pnl33.add(lbl170);
        JLabel lbl171 = new JLabel("Submit the completed application form to the Admissions Office with the required documents:");
        lbl171.setBounds(10, 27, 1260, 20);
        lbl171.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl171.setForeground(Color.BLACK);
        pnl33.add(lbl171);
        JLabel lbl172 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl172.setBounds(10, 50, 420, 17);
        lbl172.setFont(new Font("Arial", Font.BOLD, 14));
        lbl172.setForeground(Color.BLACK);
        pnl33.add(lbl172);
        JLabel lbl173 = new JLabel("Four (04) copies of Passport size colour photographs.");
        lbl173.setBounds(10, 70, 420, 16);
        lbl173.setFont(new Font("Arial", Font.BOLD, 14));
        lbl173.setForeground(Color.BLACK);
        pnl33.add(lbl173);
        JLabel lbl174 = new JLabel("Blood Group.");
        lbl174.setBounds(430, 50, 500, 17);
        lbl174.setFont(new Font("Arial", Font.BOLD, 14));
        lbl174.setForeground(Color.BLACK);
        pnl33.add(lbl174);
        JLabel lbl175 = new JLabel("Original and one set of Photocopy of all Educational Certificates & Mark sheets.");
        lbl175.setBounds(430, 70, 570, 17);
        lbl175.setFont(new Font("Arial", Font.BOLD, 14));
        lbl175.setForeground(Color.BLACK);
        pnl33.add(lbl175);
        frame.add(pnl33);




        JPanel pnl34 = new JPanel();
        pnl34.setLayout(null);
        pnl34.setBounds(250, 240, 1260, 40);
        pnl34.setOpaque(true);
        pnl34.setBackground(Color.white);
        pnl34.setVisible(false);
        JLabel lbl176 = new JLabel("LL.B. (Hons.) Admission");
        lbl176.setBounds(10, 5, 1250, 35);
        lbl176.setFont(new Font("Arial", Font.BOLD, 25));
        lbl176.setForeground(Color.BLACK);
        pnl34.add(lbl176);
        frame.add(pnl34);
        JPanel pnl35 = new JPanel();
        pnl35.setLayout(null);
        pnl35.setBounds(250, 285, 1260, 60);
        pnl35.setOpaque(true);
        pnl35.setBackground(Color.white);
        pnl35.setVisible(false);
        JLabel lbl177 = new JLabel("Duration: 4 Years");
        lbl177.setBounds(10, 5, 150, 22);
        lbl177.setFont(new Font("Arial", Font.BOLD, 17));
        lbl177.setForeground(Color.BLACK);
        pnl35.add(lbl177);
        JLabel lbl178 = new JLabel("Schedule: Day/Evening");
        lbl178.setBounds(200, 5, 350, 22);
        lbl178.setFont(new Font("Arial", Font.BOLD, 17));
        lbl178.setForeground(Color.BLACK);
        pnl35.add(lbl178);
        JLabel lbl179 = new JLabel("Total Credits: 141");
        lbl179.setBounds(10, 30, 150, 22);
        lbl179.setFont(new Font("Arial", Font.BOLD, 17));
        lbl179.setForeground(Color.BLACK);
        pnl35.add(lbl179);
        JLabel lbl180 = new JLabel("Entry Time: January/May/September");
        lbl180.setBounds(200, 30, 350, 22);
        lbl180.setFont(new Font("Arial", Font.BOLD, 17));
        lbl180.setForeground(Color.BLACK);
        pnl35.add(lbl180);
        frame.add(pnl35);

        JPanel pnl36 = new JPanel();
        pnl36.setLayout(null);
        pnl36.setBounds(250, 350, 1260, 105);
        pnl36.setOpaque(true);
        pnl36.setBackground(Color.white);
        pnl36.setVisible(false);
        JLabel lbl181 = new JLabel("Programme Summary:");
        lbl181.setBounds(10, 5, 1250, 25);
        lbl181.setFont(new Font("Arial", Font.BOLD, 20));
        lbl181.setForeground(Color.BLACK);
        pnl36.add(lbl181);
        JLabel lbl182 = new JLabel("The LL.B. (Honours) program at Metropolitan University is designed to prepare students for success in examinations conducted by the Bangladesh Judicial Service Commission and");
        lbl182.setBounds(10, 35, 1250, 20);
        lbl182.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl182.setForeground(Color.BLACK);
        pnl36.add(lbl182);
        JLabel lbl183 = new JLabel("Bangladesh Bar Council. It equips graduates to serve effectively as legal professionals and pursue higher studies in law. With a focus on developing advocates and judges of high legal");
        lbl183.setBounds(10, 55, 1250, 20);
        lbl183.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl183.setForeground(Color.BLACK);
        pnl36.add(lbl183);
        JLabel lbl184 = new JLabel(" acumen, the program aims to nurture professionals who can contribute to justice and societal well-being, upholding global standards in law and justice.");
        lbl184.setBounds(10, 75, 1250, 20);
        lbl184.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl184.setForeground(Color.BLACK);
        pnl36.add(lbl184);
        frame.add(pnl36);

        JPanel pnl37 = new JPanel();
        pnl37.setLayout(null);
        pnl37.setBounds(250, 460, 1260, 180);
        pnl37.setOpaque(true);
        pnl37.setBackground(Color.white);
        pnl37.setVisible(false);
        JLabel lbl185 = new JLabel("Fees & Funding:");
        lbl185.setBounds(10, 5, 1250, 25);
        lbl185.setFont(new Font("Arial", Font.BOLD, 20));
        lbl185.setForeground(Color.BLACK);
        pnl37.add(lbl185);
        JLabel lbl186 = new JLabel("Metropolitan University provides financial support to the students and there is a caring tuition fee policy available to give financial aid. The students having Golden  A+ in both SSC & HSC ");
        lbl186.setBounds(10, 35, 1250, 20);
        lbl186.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl186.setForeground(Color.BLACK);
        pnl37.add(lbl186);
        JLabel lbl187 = new JLabel("will be given 50% tuition waiver.");
        lbl187.setBounds(10, 55, 1250, 20);
        lbl187.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl187.setForeground(Color.BLACK);
        pnl37.add(lbl187);
        JLabel lbl188 = new JLabel("Metropolitan University has various scholarship schemes to support the students financially.");
        lbl188.setBounds(10, 75, 1250, 20);
        lbl188.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl188.setForeground(Color.BLACK);
        pnl37.add(lbl188);
        JLabel lbl189 = new JLabel("A student who has secured A+ in all the courses in three consecutive term examinations can apply for Chairman’s Scholarship. Likewise, Vice Chancellor’s Scholarship also exists for ");
        lbl189.setBounds(10, 95, 1250, 20);
        lbl189.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl189.setForeground(Color.BLACK);
        pnl37.add(lbl189);
        JLabel lbl190 = new JLabel("the students of Metropolitan University.");
        lbl190.setBounds(10, 115, 1250, 20);
        lbl190.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl190.setForeground(Color.BLACK);
        pnl37.add(lbl190);
        JLabel lbl191 = new JLabel("Admission Fee (One time): 20,000");
        lbl191.setBounds(10, 135, 320, 17);
        lbl191.setFont(new Font("Arial", Font.BOLD, 14));
        lbl191.setForeground(Color.BLACK);
        pnl37.add(lbl191);
        JLabel lbl192 = new JLabel("Registration Fee (Per term): 10,000");
        lbl192.setBounds(10, 155, 320, 17);
        lbl192.setFont(new Font("Arial", Font.BOLD, 14));
        lbl192.setForeground(Color.BLACK);
        pnl37.add(lbl192);
        JLabel lbl193 = new JLabel("BNCC Fee (One time): 100");
        lbl193.setBounds(320, 135, 320, 17);
        lbl193.setFont(new Font("Arial", Font.BOLD, 14));
        lbl193.setForeground(Color.BLACK);
        pnl37.add(lbl193);
        JLabel lbl194 = new JLabel("Campus Activities Fee (Per Month): 1,500");
        lbl194.setBounds(320, 155, 320, 17);
        lbl194.setFont(new Font("Arial", Font.BOLD, 14));
        lbl194.setForeground(Color.BLACK);
        pnl37.add(lbl194);
        JLabel lbl195 = new JLabel("Monthly Installment of Credit Fees: 6,000");
        lbl195.setBounds(670, 135, 320, 17);
        lbl195.setFont(new Font("Arial", Font.BOLD, 14));
        lbl195.setForeground(Color.BLACK);
        pnl37.add(lbl195);
        frame.add(pnl37);

        JPanel pnl38 = new JPanel();
        pnl38.setLayout(null);
        pnl38.setBounds(250, 645, 1260, 95);
        pnl38.setOpaque(true);
        pnl38.setBackground(Color.white);
        pnl38.setVisible(false);
        JLabel lbl196 = new JLabel("How to apply:");
        lbl196.setBounds(10, 5, 320, 22);
        lbl196.setFont(new Font("Arial", Font.BOLD, 18));
        lbl196.setForeground(Color.BLACK);
        pnl38.add(lbl196);
        JLabel lbl197 = new JLabel("Submit the completed application form to the Admissions Office with the required documents:");
        lbl197.setBounds(10, 27, 1260, 20);
        lbl197.setFont(new Font("Arial", Font.PLAIN, 15));
        lbl197.setForeground(Color.BLACK);
        pnl38.add(lbl197);
        JLabel lbl198 = new JLabel("Photocopies of Birth Certificate/ National ID/ Passport.");
        lbl198.setBounds(10, 50, 420, 17);
        lbl198.setFont(new Font("Arial", Font.BOLD, 14));
        lbl198.setForeground(Color.BLACK);
        pnl38.add(lbl198);
        JLabel lbl199 = new JLabel("Four (04) copies of Passport size colour photographs.");
        lbl199.setBounds(10, 70, 420, 16);
        lbl199.setFont(new Font("Arial", Font.BOLD, 14));
        lbl199.setForeground(Color.BLACK);
        pnl38.add(lbl199);
        JLabel lbl200 = new JLabel("Blood Group.");
        lbl200.setBounds(430, 50, 500, 17);
        lbl200.setFont(new Font("Arial", Font.BOLD, 14));
        lbl200.setForeground(Color.BLACK);
        pnl38.add(lbl200);
        JLabel lbl201 = new JLabel("Original and one set of Photocopy of all Educational Certificates & Mark sheets.");
        lbl201.setBounds(430, 70, 570, 17);
        lbl201.setFont(new Font("Arial", Font.BOLD, 14));
        lbl201.setForeground(Color.BLACK);
        pnl38.add(lbl201);
        frame.add(pnl38);




        String[] courses = {"Departments", "ENG", "BBA", "CSE", "EEE", "SWE", "ECO", "LLB"};
        JComboBox<String> comboBox = new JComboBox<>(courses);
        comboBox.setBounds(20, 200, 180, 40);
        comboBox.setFont(new Font("Arial", Font.BOLD, 18));
        comboBox.setBackground(Color.WHITE);
        comboBox.setForeground(Color.BLACK);
        frame.add(comboBox);
        comboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selected = (String) comboBox.getSelectedItem();

                if(selected.equals("Departments")){
                    comboBox.setSelectedIndex(0);

                    pnl.setVisible(true);
                    pnl1.setVisible(true);
                    pnl2.setVisible(true);
                    pnl3.setVisible(true);

                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl14.setVisible(false);
                    pnl15.setVisible(false);
                    pnl16.setVisible(false);
                    pnl17.setVisible(false);
                    pnl18.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);

                }
                else if(selected.equals("ENG"))
                {
                    pnl4.setVisible(true);
                    pnl5.setVisible(true);
                    pnl6.setVisible(true);
                    pnl7.setVisible(true);
                    pnl8.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("BBA"))
                {

                    pnl9.setVisible(true);
                    pnl10.setVisible(true);
                    pnl11.setVisible(true);
                    pnl12.setVisible(true);
                    pnl13.setVisible(true);

                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("CSE"))
                {

                    pnl14.setVisible(true);
                    pnl15.setVisible(true);
                    pnl16.setVisible(true);
                    pnl17.setVisible(true);
                    pnl18.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("EEE"))
                {

                    pnl19.setVisible(true);
                    pnl20.setVisible(true);
                    pnl21.setVisible(true);
                    pnl22.setVisible(true);
                    pnl23.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl14.setVisible(false);
                    pnl15.setVisible(false);
                    pnl16.setVisible(false);
                    pnl17.setVisible(false);
                    pnl18.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("SWE"))
                {


                    pnl24.setVisible(true);
                    pnl25.setVisible(true);
                    pnl26.setVisible(true);
                    pnl27.setVisible(true);
                    pnl28.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl14.setVisible(false);
                    pnl15.setVisible(false);
                    pnl16.setVisible(false);
                    pnl17.setVisible(false);
                    pnl18.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("ECO"))
                {


                    pnl29.setVisible(true);
                    pnl30.setVisible(true);
                    pnl31.setVisible(true);
                    pnl32.setVisible(true);
                    pnl33.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl14.setVisible(false);
                    pnl15.setVisible(false);
                    pnl16.setVisible(false);
                    pnl17.setVisible(false);
                    pnl18.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl34.setVisible(false);
                    pnl35.setVisible(false);
                    pnl36.setVisible(false);
                    pnl37.setVisible(false);
                    pnl38.setVisible(false);
                }
                else if(selected.equals("LLB"))
                {


                    pnl34.setVisible(true);
                    pnl35.setVisible(true);
                    pnl36.setVisible(true);
                    pnl37.setVisible(true);
                    pnl38.setVisible(true);

                    pnl.setVisible(false);
                    pnl1.setVisible(false);
                    pnl2.setVisible(false);
                    pnl3.setVisible(false);
                    pnl4.setVisible(false);
                    pnl5.setVisible(false);
                    pnl6.setVisible(false);
                    pnl7.setVisible(false);
                    pnl8.setVisible(false);
                    pnl9.setVisible(false);
                    pnl10.setVisible(false);
                    pnl11.setVisible(false);
                    pnl12.setVisible(false);
                    pnl13.setVisible(false);
                    pnl14.setVisible(false);
                    pnl15.setVisible(false);
                    pnl16.setVisible(false);
                    pnl17.setVisible(false);
                    pnl18.setVisible(false);
                    pnl19.setVisible(false);
                    pnl20.setVisible(false);
                    pnl21.setVisible(false);
                    pnl22.setVisible(false);
                    pnl23.setVisible(false);
                    pnl24.setVisible(false);
                    pnl25.setVisible(false);
                    pnl26.setVisible(false);
                    pnl27.setVisible(false);
                    pnl28.setVisible(false);
                    pnl29.setVisible(false);
                    pnl30.setVisible(false);
                    pnl31.setVisible(false);
                    pnl32.setVisible(false);
                    pnl33.setVisible(false);
                }
            }
        });


        // Programmes
        JButton btn2 = new JButton("Programmes");
        btn2.setFont(new Font("Arial", Font.BOLD, 23));
        btn2.setBounds(190, 140, 180, 40);
        btn2.setBackground(Color.CYAN);
        btn2.setForeground(Color.BLACK);
        btn2.setOpaque(true);
        frame.add(btn2);
        btn2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                comboBox.setSelectedIndex(0);

                pnl.setVisible(true);
                pnl1.setVisible(true);
                pnl2.setVisible(true);
                pnl3.setVisible(true);

                pnl4.setVisible(false);
                pnl5.setVisible(false);
                pnl6.setVisible(false);
                pnl7.setVisible(false);
                pnl8.setVisible(false);
                pnl9.setVisible(false);
                pnl10.setVisible(false);
                pnl11.setVisible(false);
                pnl12.setVisible(false);
                pnl13.setVisible(false);
                pnl14.setVisible(false);
                pnl15.setVisible(false);
                pnl16.setVisible(false);
                pnl17.setVisible(false);
                pnl18.setVisible(false);
                pnl19.setVisible(false);
                pnl20.setVisible(false);
                pnl21.setVisible(false);
                pnl22.setVisible(false);
                pnl23.setVisible(false);
                pnl24.setVisible(false);
                pnl25.setVisible(false);
                pnl26.setVisible(false);
                pnl27.setVisible(false);
                pnl28.setVisible(false);
                pnl29.setVisible(false);
                pnl30.setVisible(false);
                pnl31.setVisible(false);
                pnl32.setVisible(false);
                pnl33.setVisible(false);
                pnl34.setVisible(false);
                pnl35.setVisible(false);
                pnl36.setVisible(false);
                pnl37.setVisible(false);
                pnl38.setVisible(false);

            }
        });


        frame.setVisible(true);

    }
}
